eureka:
  client:
    service-url:
      #将Eureka客户端client注册到两台Eureka服务端server
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#  instance:
#    hostname: clientName
#修改应用的名字
spring:
  application:
    name: client


#开发环境dev ，生产环境prod